version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      site-devdeps:
        patterns: ["*"]
    labels: ["deps: site"]
    commit-message:
      prefix: "site"

  - package-ecosystem: "pip"
    directory: "/pipeline"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      pipeline-deps:
        patterns: ["*"]
    labels: ["deps: pipeline"]
    commit-message:
      prefix: "pipeline"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions:
        patterns: ["*"]
    labels: ["deps: ci"]
    commit-message:
      prefix: "ci"
